# This file builds given version of PHP and pushes it to Cachix cache.
# The following secrets need to be set:
# - “CACHIX_AUTH_TOKEN” for uploading built Nix packages to Cachix
name: Build

on:
  pull_request:
  push:

jobs:
  prepare-ci:
    name: 'Prepare actions'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Generate actions
        run: nix-shell .github/workflows/workflow-from-flake-checks.nix
  test:
    needs:
      - prepare-ci
    uses: ./.github/workflows/test.yaml
    secrets: inherit
