# This file builds given version of PHP and pushes it to Cachix cache.
# The following secrets need to be set:
# - “CACHIX_AUTH_TOKEN” for uploading built Nix packages to Cachix
name: Build

on:
  pull_request:
  push:

jobs:
  build:
    name: 'PHP ${{ matrix.php.branch }}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - branch: '8.1'
          - branch: '8.0'
          - branch: '7.4'
          - branch: '7.3'
          - branch: '7.2'
          - branch: '7.1'
          - branch: '7.0'
          - branch: '5.6'
      # We want to fix failures individually.
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Set up Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: fossar
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-shell run-flake-checks.nix --argstr branch "${{ matrix.php.branch }}"
